version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12
    working_directory: ~/repo

  docker-executor:
    docker:
      - image: cimg/python:3.12
      - image: docker:20.10.7
    working_directory: ~/repo

jobs:
  pylint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies for linting
          command: |
            pip install -r requirements.txt
            pip install pylint pylint-django
      - run:
          name: Run Pylint
          command: pylint --load-plugins=pylint_django --django-settings-module=todo.settings --disable=missing-docstring tasks/*.py

  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies for tests
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: python manage.py test

  build_and_deploy_to_dockerhub:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t kodwoessel/todoapi:${CIRCLE_SHA1} .
            docker build -t kodwoessel/todoapi:latest .
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push kodwoessel/todoapi:${CIRCLE_SHA1}
            docker push kodwoessel/todoapi:latest


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - pylint
      - test
      - build_and_deploy_to_dockerhub:
          requires:
            - test
            - pylint
